Setup Portfolio Project
Talha-Hanif5666/Portfolio-Project pull request #1
Opened 2022-10-28 13:04 UTC by Talha-Hanif5666

Project for mobile use first. In this project a template is chosen from figma and made its mobile responsive version.

2022-10-28 20:54 UTC, cynthiainga requested changes
Hi @Talha-Hanif5666, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit history ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 20:54 UTC, cynthiainga commented on index.html
> +    </div>
- [ ] The container of this section is a `section` tag. It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info 🙃 🙃

2022-10-28 20:54 UTC, cynthiainga commented on style.css
> +}
- [ ] Please kindly make sure your design stick as much as possible to the Figma design. You have some spaces to the left and to the top of your page, kindly fix it 🙃 🙃 

Your design

<img width="283" alt="Screen Shot 2022-10-28 at 22 31 40" src="https://user-images.githubusercontent.com/74501523/198728787-e200292f-387d-4800-9f31-9cfa4b50b36e.png">

Figma design

<img width="305" alt="Screen Shot 2022-10-28 at 22 42 50" src="https://user-images.githubusercontent.com/74501523/198728872-736e96b8-15a3-4400-a597-02980076fe7e.png">

2022-10-29 06:53 UTC, aimalamiri requested changes
Hi @Talha-Hanif5666, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191356050-93e2eb80-7c05-4749-92f7-8925a1fa9386.gif)


 ## Highlights

- The header section is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 06:53 UTC, aimalamiri commented on style.css
> +  font-family: 'Crete-Round', sans-serif;
Good job for using the proper font name, but you forget to include the font in your `head` tag. That's why this font is not applied. You can take it from the [google fonts](https://fonts.google.com/specimen/Crete+Round?query=Crete+Round).

![image](https://user-images.githubusercontent.com/34779928/198818205-bccf0752-aeac-499a-9413-d5e542a27c4f.png)

2022-10-29 07:58 UTC, OyePriscilla approved these changes
# Hi @Talha-Hanif5666  😄 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
The commit messages are meaningful ✅
Linters are working properly ✅
Github flow observed ✅ 

## Optional suggestions

- [ ] [optional] Please kindly take note that your commit messages should be in sentence case.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @oyepriscilla in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 08:13 UTC, merged