Pop up window
Talha-Hanif5666/Portfolio-Project pull request #9
Opened 2022-11-16 18:45 UTC by Talha-Hanif5666

In this PR, HTML content is made dynamically through Javascript code.
Javascript interaction is applied to the required content.

2022-11-16 19:29 UTC, aimalamiri requested changes
Hi @Talha-Hanif5666, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️

Good job! but it's required to validate the email does not include any uppercase letters. Kindly make sure to implement this feature.

![image](https://user-images.githubusercontent.com/34779928/202275488-f46284fe-4e23-4dc5-a3b3-c666d2d275a5.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-16 19:29 UTC, aimalamiri commented on index.html
> +    </div> -->
It's highly recommended to keep your repository as clean as possible, and removing the unused commented code will help you keep it clean. Kindly make sure to remove it.

2022-11-16 19:29 UTC, aimalamiri commented on index.html
> +    </div> -->
It's highly recommended to keep your repository as clean as possible, and removing the unused commented code will help you keep it clean. Kindly make sure to remove it.

2022-11-16 19:40 UTC, Talha-Hanif5666 commented
Thank you for your response.
I mistakenly submitted pull request on wrong activity submission link.
I want to request for pop up window project.

Can you please give back my review request?
As i mistakenly do it.
Please let me know

On Thu, 17 Nov 2022, 00:29 Aimal Amiri, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Talha-Hanif5666 <https://github.com/Talha-Hanif5666>,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> [image: AlmostThereReachGIF]
> <https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif>
> Highlights
>
>    - Good job for using the right GitHub Flow 💯
>    - Awesome file organization 🗃️
>    - Commits are descriptive and meaningful 👍
>    - Linters are properly set up and passing 🟢 👍
>
> Required Changes ♻️
>
> Good job! but it's required to validate the email does not include any
> uppercase letters. Kindly make sure to implement this feature.
>
> [image: image]
> <https://user-images.githubusercontent.com/34779928/202275488-f46284fe-4e23-4dc5-a3b3-c666d2d275a5.png>
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/Talha-Hanif5666/Portfolio-Project/pull/9#discussion_r1024418347>
> :
>
> > +        <!-- <div class="pop-up-mobile" id="popupmobile">
>
> +        <div class="pop-up-header" id="popupclosemobile">
>
> +          <h2>Multi Post Stories</h2>
>
> +          <span class="close">&times;</span>
>
> +        </div>
>
> +        <div>
>
> +          <ul class="pop-up-tags">
>
> +            <li>html</li>
>
> +            <li>Bootstrap</li>
>
> +            <li>Ruby on rails</li>
>
> +          </ul>
>
> +        </div>
>
> +        <div class="mobile-popup-img">
>
> +        <img src="Images\Mobile-popup.png" alt="popup-img.png">
>
> +        </div>
>
> +        <div class="popup-description">
>
> +          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent</p>
>
> +        </div>
>
> +        <div class="popup-buttons">
>
> +          <button id="see-live">See Live <img src="Images\mob-popup.png" alt="img.png"></button>
>
> +          <button id="see-source">See Source <img src="Images\pop-icon-github.png" alt="img.png"></button>
>
> +        </div>
>
> +    </div> -->
>
>
> It's highly recommended to keep your repository as clean as possible, and
> removing the unused commented code will help you keep it clean. Kindly make
> sure to remove it.
> ------------------------------
>
> In index.html
> <https://github.com/Talha-Hanif5666/Portfolio-Project/pull/9#discussion_r1024418533>
> :
>
> > +      <!-- <div class="pop-up-desk" id="popupdesk">
>
> +        <div class="pop-up-header-desk">
>
> +          <h2>Keeping track of hundreds  of components website</h2>
>
> +          <span class="close-desk" id="close-desk-">&times;</span>
>
> +        </div>
>
> +        <div>
>
> +          <ul class="pop-up-tags-desk">
>
> +            <li>html</li>
>
> +            <li>Bootstrap</li>
>
> +            <li>Ruby on rails</li>
>
> +          </ul>
>
> +        </div>
>
> +        <div class="desk-popup-img">
>
> +        <img src="Images\desktop-popup.png" alt="popup-img.png">
>
> +        </div>
>
> +        <div class="popup-description-desk">
>
> +          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.</p>
>
> +        </div>
>
> +        <div class="popup-buttons-desk">
>
> +          <button id="see-live-desk" class="see-live">See Live <img src="Images\mob-popup.png" alt="img.png"></button>
>
> +          <button id="see-source-desk" class="see-source">See Source <img src="Images\pop-icon-github.png" alt="img.png"></button>
>
> +        </div>
>
> +    </div> -->
>
>
> It's highly recommended to keep your repository as clean as possible, and
> removing the unused commented code will help you keep it clean. Kindly make
> sure to remove it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Talha-Hanif5666/Portfolio-Project/pull/9#pullrequestreview-1183194266>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3HSIXAKMFQ5GOJOZ2JL2ETWIUYY5ANCNFSM6AAAAAASCRRJCE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-16 20:06 UTC, addod19 requested changes
### Hi @Talha-Hanif5666, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- [ ] Linters set up and working correctly :+1: 
- [ ] The JavaScript code implements an array of objects to store JavaScript objects containing the information for each project :rocket: 
- [ ] The projects section is created dynamically with the information from the projects array :100: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Deleting all commented piece of code, it makes our code base messy and difficult to understand

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-16 20:06 UTC, addod19 commented on index.js
> +          <a class="other-content-link" id="project" href="#" >See Project</a>
- [ ] We are expected top display a particular project when we click on the `details` button. However, the pop up always displays a particular project instead of dynamically displaying it in the list of projects
![Screenshot from 2022-11-16 19-52-03](https://user-images.githubusercontent.com/46388113/202280486-bf8bcae9-0b43-40bd-a673-c2a8e4a3da94.png)
Also, because we are always popping  up the same data for different projects, the close button sometimes is not responding to close action.Let us kindly fix it

![Screenshot from 2022-11-16 19-56-46](https://user-images.githubusercontent.com/46388113/202281520-63008f1d-dbfa-482d-893b-bf327a124873.png)

2022-11-17 07:09 UTC, Davidosky007 approved these changes
Hi @Talha-Hanif5666 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Professional looking PR 👍 
* Proper use of GitHub Flow pattern 👍  
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 07:11 UTC, merged